FROM eclipse-temurin:17-jdk-focal
EXPOSE 8081
WORKDIR /app

COPY .mvn ./.mvn/
COPY mvnw pom.xml ./
COPY src ./src

RUN ./mvnw dependency:go-offline -B
RUN ./mvnw package -DskipTests

ENTRYPOINT ["java","-jar","target/demo-0.0.1-SNAPSHOT.jar"]